### ISSUE TITLE
networkLocationListener in TrackerService missing proper unsubscribing.

### ISSUE THREAD

**Issue by liinahamari** [y20k/trackbook#100]
In function removeNetworkLocationListener() of  there is unsubscribing of gpsLocationListener, instead of networkLocationListener. [Line 388.](https://github.com/y20k/trackbook/blob/0be1904cba77f17eac118378b9cca63dabf6652f/app/src/main/java/org/y20k/trackbook/TrackerService.kt#L388)

**Comment by y20k** [comment]
published in [v2.1.0](https://github.com/y20k/trackbook/releases/tag/v2.1.0)
