### ISSUE TITLE
Dutch translation - revision / request

### ISSUE THREAD

**Issue by mm4c** [y20k/trackbook#102]
Hello,
As happy user of Trackbook I have updated/revised the Dutch translation. 
At the end of the strings there were two that I can't translate however.

July 20, 1969 = in Dutch language convention that is < 20 juli 1969 >

track data missing = in Dutch language < ontbrekende track data >

greetings @mm4c

**Comment by y20k** [comment]
Hi @mm4c 

Thanks 🇳🇱 

And dont' worry. The strings you are referring to are only used on development screens as placeholder text for real data. They are marked as [translatable="false"](https://github.com/y20k/trackbook/blob/7d690dc2eb3c429ec32d1e1ed5a2ddf5446604ea/app/src/main/res/values/strings.xml#L118).
