### ISSUE TITLE
Steps taken: pedometer not available

### ISSUE THREAD

**Issue by ceidem** [y20k/trackbook#104]
I've recently changed phones to a Samsung Galaxy S20 FE 5G and now when I use this app, I never get approximate steps that I did with my old G7. Is there a setting or permission I'm missing? Does Trackbook use the steps from another app like Fitbit? However I can help, please let me know.

Thanks,
Chris

**Comment by y20k** [comment]
Hi @ceidem 

I stumbled upon this problem a while ago too. On newer Android versions the app requires a special permission to be able to access the step counter. 

A permission request is implemented in this commit [940aa22](https://github.com/y20k/trackbook/commit/940aa2209b491c4b96aad380379d08467fd05bca).

The next update of Trackbook will include this fix. But we are still working in parallel on improving the altitude calculation #99. Both fixes are in the same code base, meaning: you may need to have to wait a bit.

**Comment by ceidem** [comment]
Thank you for your response - that makes sense on why it disappeared.

**Comment by y20k** [comment]
I finally had the time to publish a new version ([v2.1.0](https://github.com/y20k/trackbook/releases/tag/v2.1.0)) of the app containing the above mentioned fix

**Comment by ceidem** [comment]
Wondetful! Thank you, I will try to test it this weekend.

Thanks again,
 - chris

On September 30, 2021 4:06:57 AM CDT, y20k ***@***.***> wrote:
>I finally had the time to publish a new version ([v2.1.0](https://github.com/y20k/trackbook/releases/tag/v2.1.0)) of the app containing the above mentioned fix 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/y20k/trackbook/issues/104#issuecomment-931097163
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
