### ISSUE TITLE
Trackbook is failing to build on F-Droid

### ISSUE THREAD

**Issue by voussoir** [y20k/trackbook#107]
Hi y20k,

I am not sure if you are already aware of this issue. Trackbook on F-Droid is stuck at 2.0.10 because 2.1.0 is failing to build.

https://monitor.f-droid.org/builds/build

https://monitor.f-droid.org/builds/log/org.y20k.trackbook/48

The majority of the errors look like SSL certificate issues and "The repository ... does no longer have a Release file", so I'm not sure if something's wrong with the build server or with Trackbook. I just thought I would bring this to your attention.

I'm really looking forward to installing 2.1.0!!

Thank you

**Comment by y20k** [comment]
I noticed that, too. But the problem has been fixed already by the fdroid folks.
