### ISSUE TITLE
Trackbock stops working as soon as screen locked

### ISSUE THREAD

**Issue by Freestyle00** [y20k/trackbook#111]
When I lock my screen the app stops putting markers and then it will produce incomplete tracks like this
![image](https://user-images.githubusercontent.com/69159664/158834507-9f2e0bf4-99d2-47fa-93eb-ef60fe3fb00d.png)

I cant also just have the screen unlocked all the time because it would kill the battery.

I found a denied pull which should solve the issue: https://github.com/y20k/trackbook/pull/94

**Comment by marcoM32** [comment]
Hi @Freestyle00 , I had the same problem, you need to make sure Trackbook is out of power saving policies.

**Comment by Freestyle00** [comment]
Ok thanks for the tip.

I have disabled everything which should hinder it. If it works, I will close the issue.

**Comment by Freestyle00** [comment]
@marcoM32 So I have tried it today but it did not work as, as soon as I lock my screen it stops tracjing again until I unlock my screen.
![Screenshot_20220320-190332_Trackbook](https://user-images.githubusercontent.com/69159664/159189203-48616616-bcad-4b09-9c4d-e449cfdafb92.png)

**Comment by robinfoxnan** [comment]
需要将APP的省电策略改一下，改为无限制；
The power saving strategy of app needs to be changed to unlimited；
and it will work

**Comment by Freestyle00** [comment]
Thanks for the answer.

that worked thanks.

Closing issue now problem sat in front of keyboard (or touchscreen in this case)
