### ISSUE TITLE
Add pace to track info

### ISSUE THREAD

**Issue by fgerling** [y20k/trackbook#112]
I'm using trackbook to track my runs. It would be awesome to see the 'pace' (for example 6:45 for 1km) for a saved track.

**Comment by mike-of-earth** [comment]
I am not sure if I should open another item, but I'd like to add to this too. Elevation gain, distance traveled. Unless I'm missing a way to view this info while recording.

**Comment by y20k** [comment]
Hi @mike-of-earth and @fgerling 

I am pretty busy in my day job at the moment. I think I do not find the time to implement this in the next couple of month. 

I like the idea though!! 

For now I will put this issue in the "enhancement, help wanted" section on the issue [Previous discussions and feature requests](https://github.com/y20k/trackbook/issues/57).

@fgerling 

What would be the right measurement unit for 'pace'? 

- km/h (or mph)
- minutes for 1 km (or 1 mile)

**Comment by y20k** [comment]
PS. Please do not feel bad. I always close feature requests that I am not going to work on in the next few month, even if they are tagged as "enhancement, help wanted". When someone picks the issue up, it will be re-opened!!
