### ISSUE TITLE
Previous track switcher a bit slow?

### ISSUE THREAD

**Issue by collectorgeneral** [y20k/trackbook#13]
As the title says, the previous track switcher appears to not be smooth. Any ideas what maybe causing it? @y20k , Are you experiencing it as well?

**Comment by y20k** [comment]
Hi @collectorgeneral 

by track switcher you mean the date drop down menu right? Which part of it exactly is slow? The menu, the act of loading of the map, moving the map around? 

Or do you mean the transition between MAP and LAST TRACKS?

**Comment by collectorgeneral** [comment]
Oh god, this is a horrible report, no details at all, sorry!

Yes, the part where you tap to show the drop down box. The rest is fine as far as I am concerned. Its more of an aesthetic issue, its just not smooth.

**Comment by y20k** [comment]
So you mean: The drop down menu is displayed smoothly. You tap on it. The menu fades out smoothly. But THEN the loading of the map is too slow?

**Comment by collectorgeneral** [comment]
I mean the other way around! When you tap, the process of displaying the drop down and then the closing is. The loading is not an issue with me.

**Comment by y20k** [comment]
Okay. Thanks for the clarification. I will look into it. There is a slight delay between tapping the menu and the menu actually being displayed.

**Comment by collectorgeneral** [comment]
Sure, I am uploading a screencast in case you want to check it out. 
[TB_Menu_Lag.zip](https://github.com/y20k/trackbook/files/839680/TB_Menu_Lag.zip)

**Comment by y20k** [comment]
the new version of trackbook ([v2.0.1](https://github.com/y20k/trackbook/releases/tag/v2.0.1)) has a list instead of a dropdown.
