### ISSUE TITLE
Delete recorded tracks

### ISSUE THREAD

**Issue by privacy-wolf** [y20k/trackbook#16]
One option I'm missing (or overlooked) is to delete a recorded track. What I would expect is a wastepin button next to the recording selection (next to the download button) - pressing it would ask for confirmation (Do you really want to delete this recording? Yes/No).

**Comment by y20k** [comment]
Hi @privacy-wolf ,

that is definitely a planned feature! There is already [code](https://github.com/y20k/trackbook/blob/576ea43c2102d83f56612d0564877d2ff680cb66/app/src/main/java/org/y20k/trackbook/MainActivityTrackFragment.java#L424) for the delete button. The UI is [not visible](https://github.com/y20k/trackbook/blob/576ea43c2102d83f56612d0564877d2ff680cb66/app/src/main/res/layout/fragment_main_track.xml#L54) at the moment. (And I am using the trashcan [icon](https://github.com/y20k/trackbook/blob/576ea43c2102d83f56612d0564877d2ff680cb66/app/src/main/res/drawable/ic_delete_forever_white_24dp.xml) => `delete forever` from [Material Icons](https://material.io/icons/)).

I am a bit reluctant. File deletion is a very simple and basic feature. But still a am a bit afraid to introduce a bug. So as soon as I have a bit more time I will implement it and test it as good as I can before releasing it.

Best regards
y20k

**Comment by y20k** [comment]
this feature is part of today's release ([v1.0.6](https://github.com/y20k/trackbook/releases/tag/v1.0.6))
