### ISSUE TITLE
Change GPX download (export) button

### ISSUE THREAD

**Issue by privacy-wolf** [y20k/trackbook#17]
To me the GPX download/export button is a bit counter-intuitive. The button is rather indicating a resorting of a list or so. What I would expect is a something like a down-arrow with a bar at the bottom - that is the icon I would usually expect for a kind of download or save option.

**Comment by y20k** [comment]
Hi @privacy-wolf ,

Thank-you. I think your observation is correct. I am using the [Material Design icon set](https://material.io/icons/). Which icon do you think is fitting? I was using the icon `import export` - maybe I should use `file download`?

**Comment by y20k** [comment]
... I think the mentioned `file download` icon is way more intuitive. I think I will go with this one.

**Old Export Icon**
![2017-06-07 10 52 19](https://user-images.githubusercontent.com/9103935/26875698-797cd860-4b83-11e7-9524-500229861791.png) 

**New Download Icon**
![2017-06-07 10 53 03](https://user-images.githubusercontent.com/9103935/26875713-7e342020-4b83-11e7-9ee1-57159c6f2c80.png)

**Comment by privacy-wolf** [comment]
Wonderful - I think this looks much better and the icon is more what one would expect.
:-)

**Comment by y20k** [comment]
the new icon is part of the current release [v1.0.4](https://github.com/y20k/trackbook/releases/tag/v1.0.4).
