### ISSUE TITLE
More intutive access to statistics

### ISSUE THREAD

**Issue by privacy-wolf** [y20k/trackbook#18]
I found it a bit hard and counter-intuitive to access the statistics of a recorded track. One has to pull-up the bar at the bottom. To make it more intuitive I would suggest to either (or both): a) to auto-pull up the statistics with a press on the statistics-icon and/or b) to place an up-arrow beside the statistics icon to indicate that one should pull it up.

**Comment by y20k** [comment]
Hi @privacy-wolf ,

> a) to auto-pull up the statistics with a press on the statistics-icon

That is a good idea. Actually I thought I made it work like this already. But it seems that only the word "Statistics" is tap-able. I will change that.

**Comment by y20k** [comment]
Okay. I changed it. This will be part of the next release. Thanks.
