### ISSUE TITLE
Why "Step Taken" is -1?

### ISSUE THREAD

**Issue by RealAquilus** [y20k/trackbook#22]
Hi! Why is it fixed at -1? I have tryied to change the parcel.writeFloat(mStepTaken); in parcel.writeFloat((float)(mTrackLength * 1.428)); (to have some step count but i know this is inaccurate).
But the situation is the same (can i have changed the wrong code? I'm still understanding the trackbook code, did i a mistake?)

**Comment by y20k** [comment]
Hi there,

Trackbook initializes the step count to _0_. 

But when it detects that a device lacks a pedometer, it sets the step count to _-1_ (see the [`startTracking`](https://github.com/y20k/trackbook/blob/16f9f0e3ab5a899aad67ae619b4551d57e692486/app/src/main/java/org/y20k/trackbook/TrackerService.java#L232) method). 

In the UI I should probably replace a _-1_ value with the message _pedometer not available_. 

For your purpose you could do the math in `stopTracking` and then call `mTrack.setStepCount(float)`

**Comment by y20k** [comment]
From [v1.0.7](https://github.com/y20k/trackbook/releases/tag/v1.0.7) on Trackbook indicates if a device is missing a pedometer - instead of just showing `-1`. Thanks for finding this error!
