### ISSUE TITLE
GPX Requires UTC for datetimes

### ISSUE THREAD

**Issue by rerobins** [y20k/trackbook#31]
See: https://en.wikipedia.org/wiki/GPS_Exchange_Format#Units

Currently GPX files are exported in the timezone of the phone.

**Comment by y20k** [comment]
Thanks for pointing that out!! I can reproduce the problem when I load an exported track into a GPX viewer.

**Comment by y20k** [comment]
The next version will correct the GPX output. If you are interested in a test version. Try this APK: [trackbook-app-test-1.1.4-01.apk](https://www.dropbox.com/s/lnrqm9ojxnj8hkc/trackbook-app-test-1.1.4-01.apk?dl=0)

If not, be patient v1.1.4 is around the corner.

**Comment by y20k** [comment]
[v1.1.4](https://github.com/y20k/trackbook/releases/tag/v1.1.4) is out. It should fix the bug.
