### ISSUE TITLE
The Trackbook Bug

### ISSUE THREAD

**Issue by beckysophie** [y20k/trackbook#32]
***Expected Behavior***

It should take me to my current/initial location 

***Actual Behavior***

Each time the button is touched, the app crashes 

***Test Tools**
* Operating system : Android 6.0
* Phone : Infinix hot s
* App version 1.1.4

***How to produce the bug***

Open the app, click on the blue button with a white dot in it. It would crash 

*Recording of the bug is shown below......*

https://youtu.be/pWWj8fcvwiU

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@beckysophie/the-trackbook-bug">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by y20k** [comment]
Hi @beckysophie,

Thanks for reporting this bug. Wow. With a screen recording! 

Trackbook needs the location service of the Android system to be enabled to do anything useful. So don't expect anything to work, if location is turned off. Trackbook shows a warning at the bottom of the screen (also visible in your video).

That said. **Trackbook should NOT crash** when you press a button! I will fix that in an upcoming release.

Thanks again & take care.

**Comment by beckysophie** [comment]
My pleasure

**Comment by y20k** [comment]
The current release (v1.1.5 ) fixes the crash you reported. THX
