### ISSUE TITLE
Lines instead of dots

### ISSUE THREAD

**Issue by rain-1** [y20k/trackbook#42]
It would be nice to have a path drown instead of just dots.

What do you think?

**Comment by Hob111** [comment]
It might help to make the route clearer if the track crossed itself but it seems a lot of work for a very small gain. If I want to look at my walks in more detail I export them to a laptop to look at them. There are plenty of web sites where gpx tracks can be displayed in many ways.

**Comment by y20k** [comment]
Aside from the fact that I didn't know how to draw a line on OSM when I started this project :-) there was another reason why I decided against drawing a line on the map:

I observed that sometimes the recorded track does not line up nicely with the streets / trails in OSM. I do not know why. The track sometimes seems to be a few pixel offset.

So I figured that dots are the easiest solution.

Anyway. I agree that lines would probably be nicer. But they need to be implemented well - or else lines might actually look worse.

**Comment by rain-1** [comment]
the [Maps](https://f-droid.org/en/packages/com.github.axet.maps/) program ([src](https://gitlab.com/axet/omim/tree/HEAD)) has a really good graphical line. I don't know how to locate exactly the code they used to do it though.

**Comment by Hob111** [comment]
@y20k "....Anyway. I agree that lines would probably be nicer. But they need to be implemented well - or else lines might actually look worse." 
I've used an app that draws lines. it can be useful but it can also look like a bag of string if the sampling is poorly chosen or the gps is a bit erratic for whatever reason.

**Comment by hockeymikey** [comment]
I had this idea the other day. Add an option so people can toggle the dots and lines. I would like to have dots and lines connecting them on mine while others may want only one or the other.
