### ISSUE TITLE
Recording start/stop button: dot icon is missing

### ISSUE THREAD

**Issue by y20k** [y20k/trackbook#43]
The dot icon on the recording start/stop button is missing under certain circumstances

@Hob111 found in #21 a way to reproduce it

> Run Trackbook, start, stop and clear a track (no need to wait for it to record any track points) then go to "Last Tracks" back to "Map" and start another track.

I did some research: This seems to be a bug in support library. I think, I will wait until it gets fixed.

see: [BUG: FloatingActionButton icon disappears after visibility change](https://issuetracker.google.com/issues/111316656)

**Comment by y20k** [comment]
I was pointed to a workaround for this bug (https://stackoverflow.com/questions/49587945/setimageresourceint-doesnt-work-after-setbackgroundtintcolorlistcolorstateli/52158081#52158081). If anyone wants to test drive this, here is an APK:

* [trackbook-app-test-1.1.11-07.apk](https://www.dropbox.com/s/0701nw8xiqqv1x1/trackbook-app-test-1.1.11-07.apk?dl=0)

**Comment by Hob111** [comment]
I've installed 1.1.11-07 and can't reproduce the bug so it looks to be fixed 😉
-- 
Sent from my Android phone using K-9 Mail.

**Comment by y20k** [comment]
Hi @Hob111, 

as far as I can see the rollback and the undoing of the rollback I needed to do in order to try to fix #44 did NOT reintroduce this bug, right?

If so, please drop me a not here.

Best regards

**Comment by Hob111** [comment]
Hi @y20k ,

I can't reproduce this bug when running trackbook-app-testing-1.1.13-002. Did someone fix the Library?

**Comment by y20k** [comment]
Not sure. But great that we don't have a feature regression here. 👍
