### ISSUE TITLE
Corrupt track files

### ISSUE THREAD

**Issue by Hob111** [y20k/trackbook#44]
V 1.1.11 is writing corrupt track files. Tracking works fine. When a track is saved then opened in "Last Tracks" the default map of Heidelberg is shown. Attempts to show statistics, share or export the track all cause Trackbook to stop.

V 1.1.10 also stops when performing operations on tracks written by v 1.1.11

V 1.1.11 reads tracks produced by previous versions of Trackbook without any problems.

I've tested this on two phones, Android 6 and Android 8.

I ran the beta, v 1.1.11-07 for several weeks without a problem. This release must differ in some way from that. :pensive:

**Comment by y20k** [comment]
Hi there, that is very unfortunate. Can you inspect the .trackbook-files written by this version of Trackbook and compare them with earlier ones? It maybe the case, that debug mode is still active. If the the newer .trackbook-files will start when opened in a test editor with the string "{"mDuration ...". Thanks

**Comment by y20k** [comment]
(PS: I seems that GitHub had a hick-up with publication times of my comments. I did found the bug **AFTER** I did the rollback to 1.1.10 code base)

**Comment by y20k** [comment]
![screenshot from 2018-11-04 10-42-47](https://user-images.githubusercontent.com/9103935/47962535-8e8c4c00-e01e-11e8-9d7e-de3d5e7047c0.png)

**Comment by y20k** [comment]
Okay since this is a very serious one, I rolled back the changes and published v1.1.10 again as v1.1.12. 

As far as I can see that files that v1.1.11 produced could not be read properly. No clue why I did not catch that during testing. 

Thank you for finding this!!!

**Comment by Hob111** [comment]
Hi, 
You've been busy this morning!

I've installed trackbook-app-testing-1.1.13-002.apk (Android 8) and it works fine. :smile: 

(BTW, I'm impressed that GitHub knows what you're going to say 6 minutes before you do. :joy:)

Presumably there is no simple way I could extract a working .gpx file from the corrupt .trackbook-file. I've looked at it with a text editor and it seems pretty unlikely.

**Comment by y20k** [comment]
v1.1.13 is out on [F-Droid](https://f-droid.org/en/packages/org.y20k.trackbook/). I think / hope this issue is now fixed.
