### ISSUE TITLE
build error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by ryanhaining** [y20k/trackbook#48]
Unable to build on both master and `v1.1.14`

```
$ ./gradlew assembleDebug
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

I noticed there's no `gradle/wrapper/gradle-wrapper.jar`

**Comment by y20k** [comment]
Hi @ryanhaining,

I have no problems checking out code from the repo and building it. I thought that `gradle/wrapper/gradle-wrapper.jar` gets automatically created, when importing the project in Android Studio. That and the fact, that F-Droid's automatic build process builds it too, never made me suspicious that any files are missing.

Anyway. I looked at an official Google [project](https://github.com/google-developer-training/android-advanced/tree/master/FragmentExample1/gradle/wrapper), and ... they include `gradle/wrapper/gradle-wrapper.jar`.

So I will upload the missing file, soon. Thanks for finding that problem!

**Comment by y20k** [comment]
Hi. Me again. I just checked out Trackbook from GitHub and let Android Studio build the source and run the app in an emulator. The strange thing: It did not create a `gradle-wrapper.jar` anywhere. The directory 
`gradle/wrapper/` still just contains a single file: `gradle-wrapper.properties`.

Any other ideas?

### Trackbook root directory 

**before built**
```
app/
assets/
AUTHORS.md
build.gradle
CONTRIBUTE.md
.gitignore
gradle/
gradle.properties
gradlew*
gradlew.bat
LICENSE.md
README.md
settings.gradle
```

**after built**
```
app/
assets/
AUTHORS.md
build.gradle
CONTRIBUTE.md
.git/
.gitignore
.gradle/
gradle/
gradle.properties
gradlew*
gradlew.bat
.idea/
LICENSE.md
local.properties
README.md
settings.gradle
trackbook.iml

```

**Comment by y20k** [comment]
Sorry that I could not provide any help.
