### ISSUE TITLE
Path editing

### ISSUE THREAD

**Issue by hockeymikey** [y20k/trackbook#56]
Sometimes my gps cuts out for whatever reason and I get some gaps in my paths. Having the ability to fix these would be great with an editor mode. It would be really simple, someone can click a dot and be able to delete it, or they can add one by clicking where they want it to be then tapping the two dots it will be placed between.

**Comment by y20k** [comment]
Hi @hockeymikey ,

while I certainly understand what you want (I found myself in similar situations before), I think that this feature is not a good fit for Trackbook. Trackbook is supposed to be a super simple app: minimal feature set, easy to use, no settings etc.. An editor would be a separate app.

Plus: I think it is not trivial to make this an easy-to-use feature

> add one by clicking where they want it to be

My toughts:
- GPS fixes and GPX waypoints contain in addition to longitude and latitude also information on altitude and time. Those cannot be set by a simple tap - but they may be computed.
- It is not obvious where a newly added waypoint would belong on the recorded track, if you just tap the screen. An additional step would be necessary like: ask the user to tap on the previous waypoint.

So. The feature can be implemented, but it is not super easy to do. And it would add a complexity to the app, that I do not really want.

I will leave this issue open for discussion, but don't be disappointed, if I eventually close it.

**Comment by Hob111** [comment]
This might sound simple but as an ex-programmer I can see it would involve a lot of code and could be an app in its own right.
....and at this point the post from @y20k arrived. It says all I was going to say (only probably more elegantly) so suffice it to say that I agree in full.

**Comment by hockeymikey** [comment]
@y20k
There's a difference between being simple and braindead (which is what not including settings is). Editors are good to be handled for advance stuff, but this is a very simple one for ironing out minor flaws.

Yeah, so just calculate a time for between those two points that make sense. That's like into to programming kind of assignment. 

That's what I said. You tap the waypoint, then tap the ones it goes between. Gotta check if the two waypoints follow each other and some validation there, but it would be super simple.

I disagree, this is all super simple, like how is it even a challenge?

@Hob111
As a current programmer I am saying it is super easy, especially considering the proposal. It's one waypoint at a time of an existing track not editing completely new paths which is tasked for an advance editor and I agree with with there. I could see the discussion for feature creep, but this is so limited it's totally within the realms of the feature set.

**Comment by y20k** [comment]
@hockeymikey
I think we will not be able to convince each other. Maybe over a beer (if you have stay in Stuttgart give me a call), but not in the issue tracker here. 
I still think that the UI of that feature is hard to implement in a way that user can understand what they need to do. 
I mean: Yes, it is not rocket science, but Trackbook is a small hobbyist project. I can only afford to spend a very small amount of my time for this. 
This was the reason why I envisioned Trackbook to be an app in the you-have-one-job category. I don't dislike complex apps at all. I just think there is a place for simple apps as well. 
Same with settings. I often like having settings in other apps. But for reasons of simplicity and ease of maintainence, I chose to try to design my apps around the concept "no settings".
As I said I do not want to convince you that I am right, which I am probably not :-) I just felt I needed to explain myself a bit. More over a beer then. Cheers.

**Comment by Hob111** [comment]
@hockeymikey Two adjacent points on the screen may not be next to one another in the data file, so "You tap the waypoint, then tap the ones it goes between" could lead to a pretty unexpected outcome. 
"Gotta check if the two waypoints follow each other and some validation there, but it would be super simple." Do you tell the user they've not chosen consecutive way points? How to you point them to the correct way points? Easy to write, not so easy to programme.  As I said, this could be an app in its own right.

This is an open source app, you're a programmer, so why not create a fork and implement these enhancements yourself and show us just how  "super easy" or "super simple" they are.

**Comment by y20k** [comment]
FYI. I am closing this issue and I am linking to it in "[Previous discussions and feature requests](https://github.com/y20k/trackbook/issues/57)".

**Comment by hockeymikey** [comment]
@Hob111 I don't want to because this is @y20k 's baby. I don't like stepping on toes or diverting time to stuff when I can be exploring new avenues for the open source community. But with the prior poor decision making for not implementing simple features (like a settings menu, which is beyond strange and ignorant) I'll probably add this to my docket some day I'm free and create a better fork.

**Comment by Hob111** [comment]
@hockeymikey I'm sure @y20k wouldn't consider a fork "treading on his toes". You don't want to divert your time but you seem happy to waste that of others 😄. Hmmm. If you think Trackbook is so poor and its creator ignorant I'm surprised you clutter your phone with it. Personally I think it's a great app that "does what it says on the tin".
