### ISSUE TITLE
Stop Action in Notification does not work as expected

### ISSUE THREAD

**Issue by y20k** [y20k/trackbook#6]
When I press "Stop" in the app's notification - and then tap the notification to get to review and save the track, then the big blue button does not offer a save option.

**Comment by collectorgeneral** [comment]
I was just about to suggest this, specially after the crashes recently. Maybe you should preserve history until the user hits the clear button. So if the app crashes/user hits stop from notification, then the track record will still be there. 

Maybe have a 'clear' flag? When the app starts recording, then the flag will be set to 'false', and if it is false, all previous recording should remain on the map. Only when the user hits the clear/clear and save button, the flag will be set to true. What are your thoughts?
