### ISSUE TITLE
Kotlin-Rewrite - Beta Test

### ISSUE THREAD

**Issue by y20k** [y20k/trackbook#66]
A couple of problems came up, when I tried to make Trackbook compatible to Android 10. Time for the big rewrite that I was holding of for too long. I will re-implement the app in Kotlin.         

In the process minSdkVersion will be bumped to 25 (Android 7.1) to make further development easier.

**Comment by y20k** [comment]
### Screenshots of the upcoming Trackbook v2.0
<a href="https://user-images.githubusercontent.com/9103935/72066043-eb009080-32df-11ea-8349-fb092879f53c.png"><img src="https://user-images.githubusercontent.com/9103935/72066043-eb009080-32df-11ea-8349-fb092879f53c.png" width="120"></a> <a href="https://user-images.githubusercontent.com/9103935/72066044-eb992700-32df-11ea-95b0-deae9a4517f4.png"><img src="https://user-images.githubusercontent.com/9103935/72066044-eb992700-32df-11ea-95b0-deae9a4517f4.png" width="120"></a><a href="https://user-images.githubusercontent.com/9103935/72066045-eb992700-32df-11ea-8a61-6d2a9f8967d1.png"><img src="https://user-images.githubusercontent.com/9103935/72066045-eb992700-32df-11ea-8a61-6d2a9f8967d1.png" width="120"></a><a href="https://user-images.githubusercontent.com/9103935/72066046-eb992700-32df-11ea-8819-fb719292216c.png"><img src="https://user-images.githubusercontent.com/9103935/72066046-eb992700-32df-11ea-8819-fb719292216c.png" width="120"></a>

**Comment by y20k** [comment]
### Beta test - How to

**1. Make a Backup**
Save a copy of the folder `/Android/data/org.y20k.trackbook/files/`

**2. Install the latest Test Release**
* [trackbook-app-testing-2.0.0-001](https://drive.google.com/open?id=1RSJAucDbdmeup7GJH1t1PrEhRXDstznS) based on [d704793](https://github.com/y20k/trackbook/tree/d704793ff12db193af618498acb82c8cdbf89a40) (2020-01-09)

**3. Give Feedback**
Just comment on this issue (#66)

**Comment by y20k** [comment]
### Revert to the last production version

**1. Uninstall Trackbook**

**2. Install a production version**
[F-Droid](https://f-droid.org/repository/browse/?fdid=org.y20k.trackbook) or [Play Store](https://play.google.com/store/apps/details?id=org.y20k.trackbook)

**3. Copy back your backup**
Copy your backup back into the folder `/Android/data/org.y20k.trackbook/files/`

**Comment by y20k** [comment]
v2.0.0 (and v2.0.1) are out. Time to close this one

**Comment by rakaandro** [comment]
Thanks, I checked out a GIT Clone and it was working "Out Of The Box" with Android Studio 3.6
