### ISSUE TITLE
DPI of tiles

### ISSUE THREAD

**Issue by GeorgeHoneywood** [y20k/trackbook#74]
Hey,

I was just wondering if something weird was going on with the scaling of tiles. As shown in the screenshot there is a lot of pixellation, and hence not much detail shown.

![Screenshot_20200621-104038_Trackbook](https://user-images.githubusercontent.com/25514836/85221539-58930b80-b3ac-11ea-8db7-18f6df7b297e.png)

Maybe this could be remedied by using the HighDPI/retina tiles, but I'm not sure if that would make the labels too little. It's only a small problem so don't worry about it if you don't have the time.

Thanks for such a useful application :)

**Comment by y20k** [comment]
Do you have those low resolution tiles all the time? I experience them sometimes, too. But in my case it is most definitely the tile server that is a bit slow.

**Comment by y20k** [comment]
PS. The should be using the correct DPI tile theoretically. See https://github.com/y20k/trackbook/blob/master/app/src/main/java/org/y20k/trackbook/ui/MapFragmentLayoutHolder.kt#L92

**Comment by GeorgeHoneywood** [comment]
Yep, those are fully loaded in, granted just before the switch to the next zoom level.

I'm curious about `        mapView.isTilesScaledToDpi = true`, I thought it would've had to be `mapView.setTilesScaledToDpi(true)` - but I have no experience with Kotlin.

Thanks again.

**Comment by y20k** [comment]
The same location with higher resolution on my phone. That's very strange.

![Screenshot_20200621-220340_Trackbook](https://user-images.githubusercontent.com/9103935/85234110-69bf3500-b40b-11ea-88af-d6c4ff377321.png)

**Comment by GeorgeHoneywood** [comment]
Hey again. Just had the time to mess around with the code, and managed to achieve my desired effect by adding a retina/HiDPI tilesource. This meant that it was correctly scaled without any pixelation.

![Screenshot_20200724-181035_Trackbook](https://user-images.githubusercontent.com/25514836/88417190-6ab3ff80-cdd9-11ea-9328-c1b517ba9097.jpg)

Irritatingly I couldn't find a fast tile server that did 2x tiles, so I had to use the really slow one provided by Osmand. If you could find a faster one I think this might be a nice improvement :)

I've included a diff below for what I changed to get that ~

```
diff --git a/app/src/main/java/org/y20k/trackbook2/ui/MapFragmentLayoutHolder.kt b/app/src/main/java/org/y20k/trackbook2/ui/MapFragmentLayoutHolder.kt
index ea6e5ac..7bfd1d2 100644
--- a/app/src/main/java/org/y20k/trackbook2/ui/MapFragmentLayoutHolder.kt
+++ b/app/src/main/java/org/y20k/trackbook2/ui/MapFragmentLayoutHolder.kt
@@ -15,7 +15,7 @@
  */
 
-package org.y20k.trackbook.ui
+package org.y20k.trackbook2.ui
 
 
 import android.Manifest
 import android.annotation.SuppressLint
@@ -31,21 +31,24 @@ import androidx.core.content.ContextCompat
 import com.google.android.material.floatingactionbutton.FloatingActionButton
 import com.google.android.material.snackbar.Snackbar
 import org.osmdroid.api.IMapController
+import org.osmdroid.tileprovider.tilesource.ITileSource
 import org.osmdroid.tileprovider.tilesource.TileSourceFactory
+import org.osmdroid.tileprovider.tilesource.XYTileSource
 import org.osmdroid.util.GeoPoint
+import org.osmdroid.views.CustomZoomButtonsController
 import org.osmdroid.views.MapView
 import org.osmdroid.views.overlay.ItemizedIconOverlay
 import org.osmdroid.views.overlay.OverlayItem
 import org.osmdroid.views.overlay.TilesOverlay
 import org.osmdroid.views.overlay.compass.CompassOverlay
 import org.osmdroid.views.overlay.compass.InternalCompassOrientationProvider
-import org.y20k.trackbook.Keys
-import org.y20k.trackbook.R
-import org.y20k.trackbook.core.Track
-import org.y20k.trackbook.helpers.AppThemeHelper
-import org.y20k.trackbook.helpers.LogHelper
-import org.y20k.trackbook.helpers.MapHelper
-import org.y20k.trackbook.helpers.PreferencesHelper
+import org.y20k.trackbook2.Keys
+import org.y20k.trackbook2.R
+import org.y20k.trackbook2.core.Track
+import org.y20k.trackbook2.helpers.AppThemeHelper
+import org.y20k.trackbook2.helpers.LogHelper
+import org.y20k.trackbook2.helpers.MapHelper
+import org.y20k.trackbook2.helpers.PreferencesHelper
 
 
 /*
@@ -60,6 +63,7 @@ data class MapFragmentLayoutHolder(var context: Context, var inflater: LayoutInf
     /* Main class variables */
     val rootView: View
     val mapView: MapView
+    var tileSource: ITileSource
     val currentLocationButton: FloatingActionButton
     val recordingButton: FloatingActionButton
     val recordingButtonSubMenu: Group
@@ -88,12 +92,19 @@ data class MapFragmentLayoutHolder(var context: Context, var inflater: LayoutInf
         locationErrorBar = Snackbar.make(mapView, String(), Snackbar.LENGTH_INDEFINITE)
 
         // basic map setup
+
+        tileSource = XYTileSource( "OSMAND_RETINA", 1, 20, 256, ".png",
+          arrayOf<String>(
+               "http://tile.osmand.net/hd/"),"© OpenStreetMap contributors")
+
+        mapView.setTileSource(tileSource)
+
         controller = mapView.controller
+
+        //mapView.setTileSource(TileSourceFactory.MAPNIK)
         mapView.isTilesScaledToDpi = true
-        mapView.setTilesScaledToDpi(true)
-        mapView.setTileSource(TileSourceFactory.MAPNIK)
         mapView.setMultiTouchControls(true)
-        mapView.zoomController.setVisibility(org.osmdroid.views.CustomZoomButtonsController.Visibility.NEVER)
+        mapView.zoomController.setVisibility(CustomZoomButtonsController.Visibility.NEVER)
         zoomLevel = PreferencesHelper.loadZoomLevel(context)
         controller.setZoom(zoomLevel)
```

Cheers again.

**Comment by y20k** [comment]
I tried the changes you suggested on my device. **The map looks beautiful now.** But the server is too slow - and I am not sure if the server is meant to be used by any other app than Osmand.

I think I am going to wait until there is a solution officially supported by the osmdroid library - preferably a solution involving SVG tiles. :-)

**Comment by GeorgeHoneywood** [comment]
Yeah, its a shame I could not seem to find any faster servers for these tiles : /

Also from looking at the osmdroid repo it doesn't look like it is likely that vector tiles are going to be added soon :(

Good luck with the app :)
