### ISSUE TITLE
Plugins and/or companion apps: a Proposal for features that add-complexity

### ISSUE THREAD

**Issue by jwmh** [y20k/trackbook#75]
Title says it all; if not:

The GNU design philosophy, AFAIUI, is:
Don't make one big app,  
to handle all use-scenarios.

Instead:
Make lots of teeny tiny apps...  Each has one function
 -- and only one function.

But:
They know how to talk with each other.
And can work together, 
as easy partners.

The extent to which an app is pared down to its most minimal is a matter of science and of art.

**Comment by y20k** [comment]
I am not what what to make of your proposal. A plug-in or API for Trackbook? I would say no to this. The app has so few users that I do not expect any developer to use this feature. But maybe there are other open APIs / exchange formats that Trackbook should support? Right now the app only supports GPX export.
