### ISSUE TITLE
"Location is turned off." notice popping up over and over

### ISSUE THREAD

**Issue by SebiderSushi** [y20k/trackbook#78]
app version: 2.0.5 from F-Droid
android version: LineageOS 15.1 (anfroid 8.1.0)

## Expected behavior
Trackbook posts the "Location is turned off." notice once and only dismisses or reposts it once the situation changes.

## Observed behavior
While a track recording is in progress and Trackbook is restarted, Trackbook reposts the "Location is turned off." notice every second. As a result, the control FAB is jumping up and down, making it very hard to operate.

## Steps to reproduce
- Open Trackbook
- Start recording a track
- Open the recents screen and swipe to remove Trackbook
- Disable location
- Re-open Trackbook

**Comment by y20k** [comment]
Thanks for finding this issue. Especially the steps to reproduce will be helpful. I am currently on vacation. I will try to fix this with the next release probably in September.

**Comment by y20k** [comment]
The bug is fixed in [v2.0.6](https://github.com/y20k/trackbook/releases/tag/v2.0.6) release. Thanks for reporting

**Comment by SebiderSushi** [comment]
v2.0.6 finelly reached F-Droid, works splendid 👍
thanks again!

**Comment by y20k** [comment]
Yeah that took quite a while this time.
