### ISSUE TITLE
[UI] Landscape rotation clips stats screen

### ISSUE THREAD

**Issue by collectorgeneral** [y20k/trackbook#8]
While testing out [this](https://github.com/y20k/trackbook/issues/7#issuecomment-273601472) from our discussion on issue #7 , I noticed that the landscape mode clips the 'Recording Stopped' part out. Not the biggest of issues, but if it is an easy fix, might want to include it in your next commit 😄  !

![screenshot_20170118-172219](https://cloud.githubusercontent.com/assets/15972594/22108538/f7c47ed4-de29-11e6-8e6a-3c0c98a721b6.png)

**Comment by y20k** [comment]
I did totally overlook that. That is an easy fix.

![phone landscape](https://cloud.githubusercontent.com/assets/9103935/22149642/3c04a1d2-df15-11e6-9b2d-a4ba3bf8863d.jpg)

While I am at it: I added a maximum width for the statistics sheet on tablets.

![tablet](https://cloud.githubusercontent.com/assets/9103935/22149678/6f91f72a-df15-11e6-8436-04f5f3ac27b1.jpg)

See [commit](https://github.com/y20k/trackbook/commit/cb56291dee6f49f18d2e0145edfd17445422fd3f).

**Comment by collectorgeneral** [comment]
@y20k Looks good 👍 .
