### ISSUE TITLE
Start and stop date and time are the same

### ISSUE THREAD

**Issue by marcoXbresciani** [y20k/trackbook#84]
After recording a track, the saved start and stop date are always the same.
![Screenshot_20201011-105627](https://user-images.githubusercontent.com/48018419/95674458-b09a8b80-0bb0-11eb-8d59-e4620e5b538f.png)

**Comment by y20k** [comment]
Oh. Thanks!! I am using my app pretty regularly. I never saw this myself. I looked into the issue and I am glad that this is only a display problem (see [here](https://github.com/y20k/trackbook/blob/026916b0d060cf868693fe9963a36b92f21d3929/app/src/main/java/org/y20k/trackbook/ui/TrackFragmentLayoutHolder.kt#L205)). Meaning the recordings have the correct end time. I will publish a small fix later today.

**Comment by y20k** [comment]
[v2.0.8](https://github.com/y20k/trackbook/releases/tag/v2.0.8) fixes the bug. Should be out on Google Play today and on F-Droid a couple of days later - depending on their build queue.

**Comment by marcoXbresciani** [comment]
> Oh. Thanks!! I am using my app pretty regularly. I never saw this myself. I looked into the issue and I am glad that this is only a display problem (see [here](https://github.com/y20k/trackbook/blob/026916b0d060cf868693fe9963a36b92f21d3929/app/src/main/java/org/y20k/trackbook/ui/TrackFragmentLayoutHolder.kt#L205)). Meaning the recordings have the correct end time. I will publish a small fix later today.

I also to use it a lot, while traveling in new places and the like, but it's the first time I've noticed the issue. 😂🤣
