### ISSUE TITLE
Proper Italian translation

### ISSUE THREAD

**Issue by marcoXbresciani** [y20k/trackbook#88]
Following https://github.com/y20k/trackbook/pull/86 I was wondering if it's better to translate "waypoint" that is currently used in Italian translations.
Technical people might understand it, but the correct Italian translation is "tappa intermedia" (or "tappe intermedie" for plural).
Not sure how these translations are managed in other tracking apps.

**Comment by marcoXbresciani** [comment]
I've applied these modifications above through the weblate site.

**Comment by y20k** [comment]
THank. I would leave it up to your judgement. In Trackbook a waypoint is a location that has been recorded as part of a longer track/hike (which consists of several waypoints).
