### ISSUE TITLE
[Enhancement] Show recorded time (and coordinates) on tap

### ISSUE THREAD

**Issue by collectorgeneral** [y20k/trackbook#9]
Now that the app is coming along (really!) well, the only feature that I can think of that would be great to have is to see data point info. 
Conceptually it appears simple. When the user taps a point, a bubble (similar to the 'Locate me' info bubble which tells you GPS/Network thing) shows up showing the date (and possibly GPS coordinates) of that particular point. In particularly long recording sessions (like the ones I have sometimes), it will be nice to know what time you got to a particular place from a particular place. 
Looking at the json files, the time appears to be saved anyway. So you can pull that info out of the temp file/recorded file and display it on the bubble.

**Comment by y20k** [comment]
Okay. The only problem I could think of would be that space is limited in those Toasts (=bubbles). Not technically but aesthetically. Displaying the time is a probably better use of this space than "Accuracy". "Accuracy" could be something that only gets displayed if a user long-pressed a dot.

**Comment by collectorgeneral** [comment]
Ah, I see. I remember in one of the apps I use the toast truncates text if it is too long (F-droid maybe?). Makes sense. 
Thats a good idea, single tap displays time; long tap displays accuracy. Alternatively, you can even have a pop-up display all the details on long tap. That box can contain things like: Date, time, accuracy, gps coordinates etc. Can have a simple button like 'Ok' or 'Close' to close the box. This might be an overkill though, I will leave that upto you to decide!

**Comment by y20k** [comment]
the change is implement. thx for the suggestion!
